services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-surge:local
    container_name: news-surge
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./logs:/app/logs
